### ISSUE TITLE
error in merge_retrieval_results_by_score

### ISSUE THREAD

**Issue by bokesyo** [OpenMatch/OpenMatch#107]
A function`src/openmatch/retriever/dense_retriever.py` -- `split_retrieve` -- `merge_retrieval_results_by_score` could not work properly when I tried to use partition to do retrieval task.

**Comment by bokesyo** [comment]
#108 the function has been fixed in this pull request.

**Comment by Yu-Shi** [comment]
Thank you for your contribution!
