### ISSUE TITLE
Question about similarity functions in (T5-)ANCE.

### ISSUE THREAD

**Issue by HugoZHL** [OpenMatch/OpenMatch#43]
In paper [ANCE ](https://arxiv.org/pdf/2007.00808.pdf?utm_source=findwork.dev&ref=findwork.dev&utm_medium=jobposting), the ANCE model uses cosine similarity; where in this repo, the T5-ANCE model seems to use dot similarity. 

Have you tried using cosine similarity in T5-ANCE? Does it perform worse than dot similarity? Are there any criteria for determining which similarity function should be used in different models?

**Comment by Yu-Shi** [comment]
ANCE uses dot product, not cosine similarity (last paragraph, page 4).

We didn't try using cosine similarity; they should have similar performance. FYI, the [BEIR paper](https://arxiv.org/pdf/2104.08663.pdf) analyzed cosine similarity vs. dot product in section 7.

**Comment by Yu-Shi** [comment]
Not in section 7, in Appendix H of its current version.
