### ISSUE TITLE
BEIR support

### ISSUE THREAD

**Issue by Yu-Shi** [OpenMatch/OpenMatch#44]

**Comment by ethankim00** [comment]
Hi, I was interested to see if there were plans to support training on BEIR dataset?

**Comment by Yu-Shi** [comment]
Hi, do you mean using the training splits provided in some of the BEIR subsets?

**Comment by ethankim00** [comment]
Yes it would be nice to have the option to finetune.,

**Comment by Yu-Shi** [comment]
Thanks for the advice! We discussed it and decided not to include the feature now, as BEIR is more like a pure evaluation benchmark for zero-shot retrieval models, and it seems that very few research uses the train splits. We may add this feature in the future, but not now.
